List college = [
  'School of Engineering',
  'Institute of Design',
  'School of Computing',
  'School of Business',
  'School of Fine Arts',
  'School of Food Technology',
];

List year = [
  'First year',
  'Second year',
  'Third year',
  'Fourth year',
  'Masters',
];
List<String> areas = [
  "Alandi Rd.",
  "Airport Rd.",
  "Aundh",
  "Baner Rd.",
  "Bavdhan",
  "Bhosari",
  "Bibawewadi",
  "Cantonment",
  "Chikhali",
  "City area",
  "Hadapsar",
  "Karvenagar",
  "Kondhwa",
  "Kothrud",
  "Magarpatta Road",
  "Nagar Rd.",
  "NIBM Rd.",
  "Pashan",
  "Paud Rd.",
  "PCMC area",
  "Rawet Rd.",
  "Satara Rd",
  "Singhgad Rd.",
  "Solapur Rd.",
  "Tingarenagar",
  "University Rd.",
  "Warje Katraj By Pass",
  "Wanowarie"
];

List pickUpPoint = [
  "Abhiruchi Multiplex",
  "Alandi gaon",
  "Akashwani (Local)",
  "Akurdi Chowk",
  "Amanora Mall",
  "Ashish Garden",
  "Aundh gaon",
  "Balaji Chowk",
  "Balaji Nagar",
  "Balewadi phata",
  "Baner Phata",
  "Big Bazar, Baner Rd.",
  "Bharati Vidyapeeth",
  "Bhumkar Chowk",
  "Bhugaon",
  "Bhusari Colony",
  "Central Mall",
  "Chandan Nagar",
  "Chandralok Hospital",
  "Chaphekar Chowk",
  "Cherry Chowk",
  "Chikhali RTO",
  "Chikhali",
  "Chinchwad St.",
  "Chrholi phata",
  "City area",
  "City Pride Chowk",
  "Cosmos Bank",
  "Dandekar Bridge",
  "Dapodi CME",
  "Dattanagar Ambegaon",
  "Dattanagar Dighi",
  "Dattawadi Corner",
  "Daulat Garden",
  "Dhayari Phata",
  "Domino's Pizza, Aundh",
  "Dorabjee Store, NIBM Rd.",
  "Fergusson College Rd.",
  "Ganeshkhind",
  "Gangadham Chowk",
  "Garware College",
  "Gurudwara, Tingarenagar",
  "Hadapsar Bhaji Mandai (Local)",
  "Hadapsar",
  "Hotel Blue Dimond",
  "Hotel Haveli Bhosari",
  "Hotel Kamini",
  "Hotel Mahabaleshwar",
  "Hotel Shivar Garden",
  "Iskon temple",
  "Ivy Estate; Wagholi",
  "Jagtap Chowk, Wanowarie",
  "Jai Ganesh Samryajya",
  "Jayashree Garden",
  "Jyoti Hotel Chowk",
  "K K Market",
  "Kalewadi Phata",
  "Kalyan Bhel",
  "Katraj Chowk",
  "Katraj",
  "Kesanand Phata",
  "Kharadi corner, Nagar Rd.",
  "Kharkee Bazar",
  "Kinara Hotel",
  "Kirtane Baug",
  "Kondhwa",
  "Kothrud Depo",
  "Kothrud",
  "Kumar Properties; E street",
  "Krome Mall (Local)",
  "Laxmi Narayan Chowk",
  "Lohia IT park",
  "Lokmanya Nagar",
  "Lulla Nagar Junction",
  "Magarpatta Main Gate",
  "Magarpatta Road",
  "Magzine Chowk",
  "Mahabaleshwar Hotel",
  "Mahesh Society",
  "Mariaai Mandir",
  "Market Yard PO",
  "Medipoint Hospital",
  "MIT Corner",
  "Mitramandal Chowk",
  "Mohammadwadi Chowk",
  "Morgasa Height Gate",
  "Morwadi Chowk",
  "Moshi",
  "Mundhawa Chowk",
  "Nagpur Chwal",
  "Nagar Rd.",
  "Nal Stop",
  "Nanded City Phata",
  "Nashik Phata",
  "Navale Bridge",
  "Nexa, Baner Road",
  "NIBM Chowk",
  "NIBM Rd.",
  "Nigadi Bhakti Shakti",
  "Nirmeetee Shoe Room",
  "Novotel / Hyat hotel",
  "Okayama Garden",
  "Pancard Club, Baner",
  "Paranjape School",
  "Parihar Chowk",
  "Pashan",
  "Paud Rd.",
  "Pawale Fly Over",
  "Phoenix Mall",
  "Phulenagar RTO",
  "Podar School",
  "Pranam Hotel (Local)",
  "Rahatani Phata",
  "Railway Gate (Local)",
  "Ramwadi Police St.",
  "Ranka Jewellers",
  "Rakshak Soc.",
  "Relience Smart, Kharadi",
  "Sai Chowk",
  "Sai Sagar",
  "Sane Chowk",
  "Sangavi Phata",
  "Santosh Hall",
  "Santosh Nagar, 16 Number",
  "Sarasbaug",
  "Sasoon Chowk",
  "SBI Sasane Nagar (Local)",
  "Sawant Petrol Pump",
  "Seven Loves Chowk",
  "SGS Mall",
  "Shatrinagar Chowk",
  "Shinde Petrol Pump",
  "Shivaji Nagar BOM",
  "Shivtirthnagar",
  "Shevalwadi Phata (Local)",
  "Shivneri Gate",
  "Shivneri Nagar",
  "Shivneri Vasahat",
  "Shivneri Wadala",
  "Shivneri Wala",
  "Shivneri",
  "Shivshankar Chowk",
  "Shivtirthnagar",
  "Shreeram Bung",
  "Shrikrishna Nagar",
  "Shubam Society",
  "Sinhgad Rd.",
  "Solapur Rd.",
  "Sri Krishna Nagar",
  "Srikrishna Nagar",
  "Swapna Shilpa",
  "Swargate S T stand",
  "Swargate",
  "Tata Guard room",
  "Tridal Hsg. Society",
  "Ubale Nagar",
  "Uttamnagar, Warje",
  "Vaiduwadi (Local)",
  "Vanaz Maruti Mandir",
  "Vishrantwadi Chowk",
  "Vitthal Mandir, Karve Nagar",
  "Wadkar Mala",
  "Wagheshwar Mandir",
  "Wakad Phata",
  "Walvekar Lawns",
  "Waraje Flyover",
  "Warje Katraj By Pass",
  "YCM Hospital"
];
List busList = [
  'a1',
  'b1',
  'c1',
  'd1',
];
List userType = [
  'Student',
  'Faculty',
];
